CREATE TABLE "maps" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "map_code" varchar UNIQUE,
  "expires" double precision
);

CREATE TABLE "layers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "map_id" integer,
  "layer_code" varchar,
  "layer_description" varchar,
  "layer_edit_code" varchar,
  "layer_participants" integer
);

CREATE TABLE "markers" (
  "map_id" integer,
  "layer_id" integer,
  "latitude" double precision,
  "longitude" double precision,
  "marker_description" varchar,
  "expires" double precision
);

CREATE UNIQUE INDEX ON "layers" ("map_id", "layer_code");

ALTER TABLE "layers" ADD FOREIGN KEY ("map_id") REFERENCES "maps" ("id") ON DELETE CASCADE;

ALTER TABLE "markers" ADD FOREIGN KEY ("map_id") REFERENCES "maps" ("id") ON DELETE CASCADE;

ALTER TABLE "markers" ADD FOREIGN KEY ("layer_id") REFERENCES "layers" ("id") ON DELETE CASCADE;
